services:
  - type: web
    runtime: docker
    name: imdb-actor-ratings
    repo: https://github.com/markusait/imdb-actor-ratings
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_MODE
        value: tmdb-supabase-tomhanks
      - key: SUPABASE_URL
        value: https://jskzxrrntdfaumzkbvly.supabase.co
      - key: SUPABASE_RATINGS_TABLE
        value: ratings
      - key: TMDB_API_KEY
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /
